version: '3.7'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ../pkg/migrations/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: payment_user_go
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: payment_db_go
